# Generated by Django 6.0.6 on 2026-06-22 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('saving', 'Saving')], max_length=20)),
                ('presupuesto_mensual', models.BigIntegerField(blank=True, null=True)),
                ('presupuesto_semanal', models.BigIntegerField(blank=True, null=True)),
                ('color_hex', models.CharField(default='#3A86FF', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability')], default='asset', max_length=20)),
                ('balance_inicial', models.BigIntegerField(default=0)),
                ('color_hex', models.CharField(default='#3A86FF', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(blank=True, default='', max_length=256)),
                ('periodo_inicio', models.PositiveSmallIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('monto', models.BigIntegerField()),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('saving', 'Saving')], max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_destino', to='core.cuenta')),
                ('cuenta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_origen', to='core.cuenta')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha', '-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_categorias', to='core.categoria')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_categorias', to='core.transaccion')),
            ],
            options={
                'verbose_name': 'Categoría de transacción',
                'verbose_name_plural': 'Categorías de transacciones',
                'unique_together': {('transaccion', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='transaccion',
            name='categorias',
            field=models.ManyToManyField(blank=True, through='core.TransaccionCategoria', to='core.categoria'),
        ),
        migrations.CreateModel(
            name='TransaccionRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('monto', models.BigIntegerField()),
                ('tipo', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('saving', 'Saving')], max_length=20)),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='mensual', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrentes_destino', to='core.cuenta')),
                ('cuenta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrentes_origen', to='core.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción recurrente',
                'verbose_name_plural': 'Transacciones recurrentes',
                'ordering': ['nombre'],
            },
        ),
    ]
