# Generated by Django 6.0.6 on 2026-06-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('ahorro', 'Ahorro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso'), ('ahorro', 'Ahorro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccionrecurrente',
            name='tipo',
            field=models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso'), ('ahorro', 'Ahorro')], max_length=20),
        ),
    ]
