# Generated by Django 6.0.6 on 2026-08-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usercredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionrecurrente',
            name='dia_ejecucion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccionrecurrente',
            name='ultima_ejecucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
