# Generated by Django 6.0.6 on 2026-09-24 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def asignar_usuario(apps, schema_editor):
    """Copia el dueño desde la cuenta de origen o, si no hay, la de destino."""
    Transaccion = apps.get_model('core', 'Transaccion')
    Cuenta = apps.get_model('core', 'Cuenta')
    for campo in ('cuenta_origen', 'cuenta_destino'):
        Transaccion.objects.filter(usuario__isnull=True, **{f'{campo}__isnull': False}).update(
            usuario_id=models.Subquery(
                Cuenta.objects.filter(pk=models.OuterRef(campo)).values('usuario_id')[:1]
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfilusuario_webauthn_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AddField(
            model_name='transaccion',
            name='recurrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='core.transaccionrecurrente'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['usuario', '-fecha', '-id'], name='trans_usuario_fecha'),
        ),
        migrations.AddConstraint(
            model_name='transaccion',
            constraint=models.UniqueConstraint(condition=models.Q(('recurrente__isnull', False)), fields=('recurrente', 'fecha'), name='recurrente_una_vez_por_dia'),
        ),
        # Al final: en PostgreSQL no se puede alterar la tabla después de un UPDATE
        # con FKs diferidas dentro de la misma transacción.
        migrations.RunPython(asignar_usuario, migrations.RunPython.noop),
    ]
