# Generated by Django 6.0.6 on 2026-09-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaccion_usuario_recurrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='cupo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='dia_corte',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='dia_pago',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('credito', 'Tarjeta de crédito')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso'), ('ahorro', 'Ahorro'), ('transferencia', 'Transferencia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccionrecurrente',
            name='tipo',
            field=models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso'), ('ahorro', 'Ahorro'), ('transferencia', 'Transferencia')], max_length=20),
        ),
    ]
