# Generated by Django 6.0.6 on 2026-09-24 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tarjetas_credito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='terminaciones',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='token_ingesta',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='token_ingesta_creado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='token_ingesta_usado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('sms', 'SMS del banco')], default='manual', max_length=10),
        ),
        migrations.CreateModel(
            name='MensajeBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(blank=True, default='', max_length=40)),
                ('texto', models.TextField()),
                ('huella', models.CharField(max_length=64)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('pendiente', 'Por revisar'), ('descartado', 'Descartado')], default='pendiente', max_length=12)),
                ('metodo', models.CharField(choices=[('patron', 'Patrón conocido'), ('ia', 'IA'), ('ninguno', 'No reconocido')], default='ninguno', max_length=10)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('motivo', models.CharField(blank=True, default='', max_length=200)),
                ('transaccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='core.transaccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_banco', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje del banco',
                'verbose_name_plural': 'Mensajes del banco',
                'ordering': ['-recibido_en'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'huella'), name='mensaje_unico_por_usuario')],
            },
        ),
    ]
