# Generated by Django 6.0.6 on 2026-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ingesta_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='incluir_en_disponible',
            field=models.BooleanField(default=True),
        ),
    ]
