# Generated by Django 6.0.6 on 2026-09-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_incluir_en_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='novedades_vistas',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cuotas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
