# Generated by Django 6.0.6 on 2026-09-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_novedades_y_cuotas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='incluir_en_disponible',
        ),
    ]
