# Generated by Django 6.0.6 on 2026-09-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_quitar_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_clave', models.CharField(max_length=150, unique=True)),
                ('fallidos', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sesiones_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
